CC=g++
CFLAGS=-Wall -std=c++14

all: ejercicio1 ejercicio2
	@echo "Se han generado todos los ejercicios."

ejercicio1:
	@${CC} ${CFLAGS} -o ej1 Ejercicio1.cpp
	@echo "Se ha generado ./ej1"

ejercicio2:
	@${CC} ${CFLAGS} -o ej2 Ejercicio2.cpp
	@echo "Se ha generado ./ej2"