CC=g++
CFLAGS=-Wall -std=c++14

all: simple01 simple02 simple03
	@echo "Se han creado 3 archivos"

simple01:
	@${CC} ${CFLAGS} -o s01 Simple01.cpp
	@echo "Se ha creado ./s01"
	
simple02:
	@${CC} ${CFLAGS} -o s02 Simple02.cpp
	@echo "Se ha creado ./s02"
	
simple03:
	@${CC} ${CFLAGS} -o s03 Simple03.cpp
	@echo "Se ha creado ./s03"