CC=g++
CFLAGS=-Wall -std=c++14

all: simple01 simple02
	@echo "Se han creado 2 archivos"

simple01:
	@${CC} ${CFLAGS} -o s01 Simple01.cpp
	@echo "Se ha creado ./s01"
	
simple02:
	@${CC} ${CFLAGS} -o s02 Simple02.cpp
	@echo "Se ha creado ./s02"
