CC=g++
CFLAGS=-Wall -std=c++14

all: ejercicio1 ejercicio2
	@echo "Se han generado todos los ejercicios."

ejercicio1:
	@${CC} ${CFLAGS} "Ejercicio 1/Ejercicio1_c.cpp" "Ejercicio 1/nodoArbol.cpp" -o ej1 
	@echo "Se ha generado ./ej1"

ejercicio2:
	@${CC} ${CFLAGS} "Ejercicio 2/Ejercicio2_c.cpp" "Ejercicio 2/Arbol.cpp" "Ejercicio 2/Fila.cpp" -o ej2 
	@echo "Se ha generado ./ej2"