# Esto es un comentario

	# Aqui van nuestras asignaciones previas
CC=g++
CFLAGS=-Wall -std=c++14

# El símbolo '@' evitará que el comando se escriba 
# antes de ejecutarse

# Como en python, es importante la identación
# Evitar ambigüedad

all: ejemplo1
	@echo "Creacion finalizada"

# ${var} será la syntax para que el programa reemplace según corresponda
ejemplo1:
	@${CC} ${CFLAGS} -o ej1 ejemplo1.cpp 
	@echo "ej1 generado"